from tkinter import*

wind = Tk()
wind.geometry("400x300+10+10")
wind.title("Grid Manager")
tx1 = Entry(wind, bd=3)
tx1.grid(row=0, column=0, sticky=N)
tx1.insert(0, "row 0, column 0")
tx2 = Entry(wind, bd=3)
tx2.grid(row=0, column=1, sticky=N,rowspan=2)
tx2.insert(0, "row 0, column 1")
tx3 = Entry(wind, bd=3)
tx3.grid(row=0, column=2, sticky=N)
tx3.insert(0, "row 0, column 2")
tx4 = Entry(wind, bd=3)
tx4.grid(row=1, column=0, sticky=N)
tx4.insert(0, "row 0, column 0")
tx5 = Entry(wind, bd=3)
tx5.grid(row=2, column=0, sticky=N,rowspan=2)
tx5.insert(0, "row 0, column 1")
tx7 = Entry(wind, bd=3)
tx7.grid(row=1, column=1, sticky=N)
tx7.insert(0, "row 0, column 0")
tx8 = Entry(wind, bd=3)
tx8.grid(row=2, column=2, sticky=N,rowspan=2)
tx8.insert(0, "row 0, column 1")
tx9 = Entry(wind, bd=3)
tx9.grid(row=2, column=1, sticky=N)
tx9.insert(0, "row 0, column 0")
tx10 = Entry(wind, bd=3)
tx10.grid(row=1, column=2, sticky=N,rowspan=2)
tx10.insert(0, "row 0, column 1")
wind.mainloop()
